### ISSUE TITLE
No GetHeightAt(pos) function exposed

### ISSUE THREAD

**Issue by darrylryan** [Zylann/godot_heightmap_module#17]
I thought I'd try setting the player position to the terrain height as a workaround for the collider stuff not being fully finished yet, but I realised there's no GetHeightAt function exposed yet.

**Comment by Zylann** [comment]
Yeah it can be done by fetching height in the appropriate texture in HeightMapData but it's not exposed to GDScript yet.
It sounds easy now because HeightMapData is just a bunch of textures, which you need to get pixels from. Surprisingly, it's not as simple as it sounds.

I didnt do that yet in this way because the physics use case may be implemented automatically eventually, and then if you need to get the height at a given position, you would basically query the physics.
If you try to do this in script, it can take you an awful lot of RAM and CPU because it means the heights image should be entirely loaded in RAM, then you need to copy all of it into a `PoolRealArray` which will triple memory usage (heights are 16-bit, floats are 32), or even sextuple if that array ends up being copied temporarily as a result of Copy-On-Write or the internal Bullet system. That might be okay for small terrains but not for 4096x4096 ones ^^"
Also a `get_height_at` function would be very inefficient if the underlying image isn't locked, so I would need to expose this as well.
The easiest would be to simply make a getter that returns the heights image, however it's also dangerous because you can't do anything you want with that image (like, writing to it or resizing it could cause Copy-on-Write again, or a desync with the inner workings).

So currently, something like that could be done:

```cpp
real_t HeightMapData::lock_heights() {
	ERR_FAIL_COND(_images[CHANNEL_HEIGHT].is_null(), 0);
	return _images[CHANNEL_HEIGHT]->lock();
}
real_t HeightMapData::get_height_at(int x, int y) {
	ERR_FAIL_COND(_images[CHANNEL_HEIGHT].is_null(), 0);
	return _images[CHANNEL_HEIGHT]->get_pixel(x, y).r; // May also change in the future
}
real_t HeightMapData::unlock_heights() {
	ERR_FAIL_COND(_images[CHANNEL_HEIGHT].is_null(), 0);
	return _images[CHANNEL_HEIGHT]->unlock();
}
```

However you still need extra care to unlock after use heheh

I eventually might make a `HeightMapTool` class similar to `SurfaceTool` that can let you access the data more efficiently in the future, especially if the heightmap is streamed, which would mean not all of the heights are available at a given time due to LOD (which mean the HeightMap would give you an approximate rather than the real value).

**Comment by darrylryan** [comment]
@Zylann Couldn't we just do this?

```
real_t HeightMapData::get_height_at(int x, int y) {
	ERR_FAIL_COND(_images[CHANNEL_HEIGHT].is_null(), 0);
         _images[CHANNEL_HEIGHT]->lock();
         real_t height = _images[CHANNEL_HEIGHT]->get_pixel(x, y).r; // May also change in the future
        _images[CHANNEL_HEIGHT]->unlock();
	return height;
}
```

**Comment by Zylann** [comment]
@darrylryan it would work, but will be even slower because you would lock and unlock the image for hundreds of thousands of pixels (there is a reason why Image doesn't do this in `get_pixel` in the first place)

**Comment by Zylann** [comment]
I just realized you weren't using physics in your question, so locking once every frame for one pixel would be fine actually. Sorry for that...
However it still means the texture has to be loaded both in VRAM and in RAM for you to access the pixels on CPU.

**Comment by Zylann** [comment]
@darrylryan I just added two functions to get height at a given position.
The one you may get interested in is `get_interpolated_height_at`: https://github.com/Zylann/godot_heightmap_module/commit/b299c6d38be0b8165854b8ce69a162e19e030fbc#diff-d19cd82b461e5598eb32a078bac4df36R182

I didn't have time to test them though, feel free to try them

**Comment by darrylryan** [comment]
@Zylann Whoop! Works a treat, I can now run around on the terrain :)
I use physics for all movement except if the ray cast downwards from the feet doesnt hit any mesh I set its height to the get_interpolated_height_at of the terrain... voila, works :)

Only slight issue with that function is that it doesn't take the translation/scaling/rotation into account.

**Comment by Zylann** [comment]
@darrylryan yeah it doesn't take scale/position into account because it's on the resource, not the node. If you want to take it into account you need to transform your position to local coordinates:

```gdscript
var to_local = heightmap.get_global_transform().affine_inverse();
var local_pos = to_local.xform(global_pos);
heightmap.get_data().get_interpolated_position_at(local_pos)
```
