### ISSUE TITLE
Error while building with clang

### ISSUE THREAD

**Issue by Schmetzler** [Zylann/godot_heightmap_module#3]
I got this error while building with llvm:
```
modules/hterrain/height_map.cpp:232:36: error: expected '(' for function-style
      cast or type construction
                        for_all_chunks(EnterWorldAction { world });
                                       ~~~~~~~~~~~~~~~~ ^
modules/hterrain/height_map.cpp:241:42: error: expected '(' for function-style
      cast or type construction
                        for_all_chunks(TransformChangedAction { &world_t...
                                       ~~~~~~~~~~~~~~~~~~~~~~ ^
modules/hterrain/height_map.cpp:247:43: error: expected '(' for function-style
      cast or type construction
                        for_all_chunks(VisibilityChangedAction { visible });
                                       ~~~~~~~~~~~~~~~~~~~~~~~ ^
```

You should use a Constructor for those Actions as you do in `height_map_brush.cpp` for Operations with more than one input.

I add patches with the changes I did
[patches.zip](https://github.com/Zylann/godot_heightmap_module/files/1184845/patches.zip)

**Comment by Zylann** [comment]
These are struct initializers. Aren't they supported in C++? And even in C?

**Comment by Zylann** [comment]
Ah, I know why, these have non-POD attributes. I'll change this soon.

Edit: I don't get why these compile fine in MSVC and GCC. I didn't make constructors here because they are not really needed if you consider initializers, they would be just repetition that isn't really worth it.
For non-POD stuff such as Ref I understand, which is why I do it in `height_map_brush.cpp`.
But... booleans? Pointers? Why these aren't working? Oo
Did you try removing struct names?

I'll change all of them to use constructors I think.

**Comment by Zylann** [comment]
I made the changes in 6cb0954c1e1edeb88ce1e0501d5e39396dec2e1b, let me know if it works

**Comment by Schmetzler** [comment]
Yes now it builds without issues.. thank you.
