### ISSUE TITLE
Crash out of boundaries

### ISSUE THREAD

**Issue by jospic** [Zylann/godot_heightmap_module#5]
Hello, I would like to let you that Godot crashes when modeling tools (add, sub, etc.) come out of the boundaries of the terrain.
Thanks.
-j

**Comment by Zylann** [comment]
Is it doing it at any boundary (north, south, east, west) or only some of them?

**Comment by jospic** [comment]
This is the situation...

![terrain_crash](https://user-images.githubusercontent.com/22050804/29324603-fb61e504-81e4-11e7-8829-2451e22ce097.png)

**Comment by Zylann** [comment]
I submitted a fix

**Comment by jospic** [comment]
Well, it works! 
But sorry, I don't understand how to apply a texture to terrain. In my case it appears all in black. Also, it seems that the "Color paint" command don't work. Should a color picker come out, right? But unfortunately nothing happens...
Thanks for your attention.
-j

**Comment by Zylann** [comment]
At the moment, any texturing requires to setup a custom shader, because there are maaaany ways to texture a terrain. I have a generic way in mind with the classic 4-color channel = 4 textures but it's not always the best one depending on the game. The technique used in the GDScript version demo had 18 textures, but was hacky and quite inefficient (and could be considered buggy for some textures), but it can also be accomplished in this module as well using color paint.
Color paint should work but indeed it lacks a color picker...

**Comment by Zylann** [comment]
If you have a requirement about texturing I suggest you open another issue
